-- Documents Module Tables Creation Script
-- Run this script to create all necessary tables for the Documents Module

-- Document Categories Table
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DocumentCategories]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[DocumentCategories] (
        [Id] INT PRIMARY KEY IDENTITY(1,1),
        [CategoryName] NVARCHAR(200) NOT NULL,
        [Description] NVARCHAR(MAX) NULL,
        [TenantId] INT NOT NULL,
        [CreatedBy] INT NOT NULL,
        [CreatedDate] DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
        [IsActive] BIT NOT NULL DEFAULT 1,
        CONSTRAINT [UQ_DocumentCategories_Name_Tenant] UNIQUE ([CategoryName], [TenantId])
    );
    
    CREATE INDEX [IX_DocumentCategories_TenantId] ON [dbo].[DocumentCategories]([TenantId]);
END
GO

-- Documents Table
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Documents]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[Documents] (
        [Id] INT PRIMARY KEY IDENTITY(1,1),
        [DocumentName] NVARCHAR(500) NOT NULL,
        [Description] NVARCHAR(MAX) NULL,
        [DocumentType] NVARCHAR(100) NOT NULL DEFAULT 'Simple',
        [CategoryId] INT NULL,
        [FileExtension] NVARCHAR(50) NULL,
        [MimeType] NVARCHAR(100) NULL,
        [TenantId] INT NOT NULL,
        [CreatedBy] INT NOT NULL,
        [CreatedDate] DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
        [ModifiedBy] INT NULL,
        [ModifiedDate] DATETIME2 NULL,
        [IsActive] BIT NOT NULL DEFAULT 1,
        [IsDeleted] BIT NOT NULL DEFAULT 0,
        [Tags] NVARCHAR(MAX) NULL,
        [RelatedEntityType] NVARCHAR(100) NULL,
        [RelatedEntityId] INT NULL,
        [RequiresVersionControl] BIT NOT NULL DEFAULT 0,
        [DocumentNumber] NVARCHAR(50) NULL,
        [IsDocumentNumberAutoGenerated] BIT NOT NULL DEFAULT 1,
        [CurrentVersionNumber] INT NULL,
        [CurrentVersionId] INT NULL,
        CONSTRAINT [FK_Documents_Category] FOREIGN KEY ([CategoryId]) REFERENCES [dbo].[DocumentCategories]([Id]) ON DELETE SET NULL,
        CONSTRAINT [FK_Documents_CurrentVersion] FOREIGN KEY ([CurrentVersionId]) REFERENCES [dbo].[DocumentVersions]([Id]) ON DELETE SET NULL
    );
    
    CREATE INDEX [IX_Documents_TenantId_IsDeleted_IsActive] ON [dbo].[Documents]([TenantId], [IsDeleted], [IsActive]);
    CREATE INDEX [IX_Documents_RelatedEntity] ON [dbo].[Documents]([RelatedEntityType], [RelatedEntityId]);
END
GO

-- Document Versions Table (for versioned documents)
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DocumentVersions]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[DocumentVersions] (
        [Id] INT PRIMARY KEY IDENTITY(1,1),
        [DocumentId] INT NOT NULL,
        [VersionNumber] INT NOT NULL,
        [FileName] NVARCHAR(500) NOT NULL,
        [FilePath] NVARCHAR(1000) NOT NULL,
        [FileSize] BIGINT NOT NULL,
        [FileHash] NVARCHAR(64) NULL,
        [MimeType] NVARCHAR(100) NULL,
        [UploadedBy] INT NOT NULL,
        [UploadedDate] DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
        [VersionNotes] NVARCHAR(MAX) NULL,
        [IsCurrentVersion] BIT NOT NULL DEFAULT 0,
        [TenantId] INT NOT NULL,
        CONSTRAINT [FK_DocumentVersions_Document] FOREIGN KEY ([DocumentId]) REFERENCES [dbo].[Documents]([Id]) ON DELETE CASCADE,
        CONSTRAINT [UQ_DocumentVersions_Document_Version] UNIQUE ([DocumentId], [VersionNumber])
    );
    
    CREATE INDEX [IX_DocumentVersions_DocumentId] ON [dbo].[DocumentVersions]([DocumentId]);
    CREATE INDEX [IX_DocumentVersions_TenantId] ON [dbo].[DocumentVersions]([TenantId]);
END
GO

-- Document Files Table (for simple/non-versioned files)
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DocumentFiles]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[DocumentFiles] (
        [Id] INT PRIMARY KEY IDENTITY(1,1),
        [DocumentId] INT NOT NULL,
        [FileName] NVARCHAR(500) NOT NULL,
        [FilePath] NVARCHAR(1000) NOT NULL,
        [FileSize] BIGINT NOT NULL,
        [FileHash] NVARCHAR(64) NULL,
        [MimeType] NVARCHAR(100) NULL,
        [UploadedBy] INT NOT NULL,
        [UploadedDate] DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
        [TenantId] INT NOT NULL,
        CONSTRAINT [FK_DocumentFiles_Document] FOREIGN KEY ([DocumentId]) REFERENCES [dbo].[Documents]([Id]) ON DELETE CASCADE
    );
    
    CREATE INDEX [IX_DocumentFiles_DocumentId] ON [dbo].[DocumentFiles]([DocumentId]);
    CREATE INDEX [IX_DocumentFiles_TenantId] ON [dbo].[DocumentFiles]([TenantId]);
END
GO

-- Document Access Log Table (audit trail)
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DocumentAccessLog]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[DocumentAccessLog] (
        [Id] INT PRIMARY KEY IDENTITY(1,1),
        [DocumentId] INT NOT NULL,
        [VersionId] INT NULL,
        [UserId] INT NOT NULL,
        [Action] NVARCHAR(50) NOT NULL,
        [ActionDate] DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
        [IPAddress] NVARCHAR(50) NULL,
        [UserAgent] NVARCHAR(500) NULL,
        [TenantId] INT NOT NULL,
        CONSTRAINT [FK_DocumentAccessLog_Document] FOREIGN KEY ([DocumentId]) REFERENCES [dbo].[Documents]([Id]) ON DELETE CASCADE,
        CONSTRAINT [FK_DocumentAccessLog_Version] FOREIGN KEY ([VersionId]) REFERENCES [dbo].[DocumentVersions]([Id]) ON DELETE SET NULL
    );
    
    CREATE INDEX [IX_DocumentAccessLog_DocumentId_ActionDate] ON [dbo].[DocumentAccessLog]([DocumentId], [ActionDate]);
    CREATE INDEX [IX_DocumentAccessLog_TenantId] ON [dbo].[DocumentAccessLog]([TenantId]);
END
GO

-- Note: The foreign key constraint FK_Documents_CurrentVersion references DocumentVersions table
-- which is created after Documents table, so we need to add it separately
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Documents]') AND type in (N'U'))
AND EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DocumentVersions]') AND type in (N'U'))
AND NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_Documents_CurrentVersion')
BEGIN
    ALTER TABLE [dbo].[Documents]
    ADD CONSTRAINT [FK_Documents_CurrentVersion] FOREIGN KEY ([CurrentVersionId]) REFERENCES [dbo].[DocumentVersions]([Id]) ON DELETE SET NULL;
END
GO

-- Add DocumentNumber and IsDocumentNumberAutoGenerated columns if they don't exist (for existing tables)
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Documents]') AND type in (N'U'))
BEGIN
    -- Add DocumentNumber column if it doesn't exist
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[Documents]') AND name = 'DocumentNumber')
    BEGIN
        ALTER TABLE [dbo].[Documents]
        ADD [DocumentNumber] NVARCHAR(50) NULL;
        PRINT 'Added DocumentNumber column to Documents table';
    END

    -- Add IsDocumentNumberAutoGenerated column if it doesn't exist
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[Documents]') AND name = 'IsDocumentNumberAutoGenerated')
    BEGIN
        ALTER TABLE [dbo].[Documents]
        ADD [IsDocumentNumberAutoGenerated] BIT NOT NULL DEFAULT 1;
        PRINT 'Added IsDocumentNumberAutoGenerated column to Documents table';
    END
END
GO

-- Add unique index for DocumentNumber (per tenant, excluding deleted)
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Documents]') AND type in (N'U'))
AND EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[Documents]') AND name = 'DocumentNumber')
AND NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_Documents_DocumentNumber_TenantId')
BEGIN
    CREATE UNIQUE INDEX [IX_Documents_DocumentNumber_TenantId] 
    ON [dbo].[Documents]([DocumentNumber], [TenantId]) 
    WHERE [DocumentNumber] IS NOT NULL AND [IsDeleted] = 0;
    PRINT 'Created unique index IX_Documents_DocumentNumber_TenantId';
END
GO

PRINT 'Documents Module tables created successfully!';

