using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CimmpleAPI.Data.Models
{
    [Table("Documents")]
    public class Document
    {
        [Key]
        public int Id { get; set; }
        
        [Required]
        [MaxLength(500)]
        public string DocumentName { get; set; }
        
        public string? Description { get; set; }
        
        [MaxLength(100)]
        public string DocumentType { get; set; } = "Simple"; // "Versioned" or "Simple"
        
        public int? CategoryId { get; set; }
        
        [MaxLength(50)]
        public string? FileExtension { get; set; }
        
        [MaxLength(100)]
        public string? MimeType { get; set; }
        
        [Required]
        public int TenantId { get; set; }
        
        [Required]
        public int CreatedBy { get; set; }
        
        [Required]
        public DateTime CreatedDate { get; set; } = DateTime.UtcNow;
        
        public int? ModifiedBy { get; set; }
        
        public DateTime? ModifiedDate { get; set; }
        
        public bool IsActive { get; set; } = true;
        
        public bool IsDeleted { get; set; } = false;
        
        public string? Tags { get; set; } // JSON array of tags
        
        [MaxLength(100)]
        public string? RelatedEntityType { get; set; } // e.g., "CustomerOrder", "JobOrder", "Vendor"
        
        public int? RelatedEntityId { get; set; }
        
        [Required]
        public bool RequiresVersionControl { get; set; } = false;
        
        [MaxLength(50)]
        public string? DocumentNumber { get; set; } // e.g., "DOC-2024-0001" or custom number
        
        public bool IsDocumentNumberAutoGenerated { get; set; } = true;
        
        public int? CurrentVersionNumber { get; set; }
        
        public int? CurrentVersionId { get; set; }

        // Navigation properties
        [ForeignKey("CategoryId")]
        public DocumentCategory? Category { get; set; }
        
        [ForeignKey("CurrentVersionId")]
        public DocumentVersion? CurrentVersion { get; set; }
        
        public ICollection<DocumentVersion> Versions { get; set; } = new List<DocumentVersion>();
        public ICollection<DocumentFile> Files { get; set; } = new List<DocumentFile>();
    }
}

