/**
 * Parse shop-floor step scan codes generated by Cimmple_UI / API PDF helpers.
 * Format: cimmple://jo/{jobOrderId}/step/{stepId}
 */
export type ParsedStepScanCode = {
  jobOrderId: number;
  stepId: number;
};

const STEP_SCAN_RE = /^cimmple:\/\/jo\/(\d+)\/step\/(\d+)$/i;

export function parseStepScanCode(raw: string): ParsedStepScanCode | null {
  const text = (raw || "").trim();
  if (!text) return null;

  const match = STEP_SCAN_RE.exec(text);
  if (!match) return null;

  const jobOrderId = Number(match[1]);
  const stepId = Number(match[2]);
  if (!Number.isFinite(jobOrderId) || jobOrderId <= 0) return null;
  if (!Number.isFinite(stepId) || stepId <= 0) return null;

  return { jobOrderId, stepId };
}
