import { GlobalSearchResults } from "../Services/GlobalSearchService";

/** Single source of truth: dropdown render order and Enter-to-open first result. */
export const GLOBAL_SEARCH_CATEGORY_ORDER: (keyof GlobalSearchResults)[] = [
  "customers",
  "vendors",
  "products",
  "rawMaterials",
  "orders",
  "quotations",
  "invoices",
  "jobOrders",
  "banks",
  "workstations",
  "locations",
  "processes",
  "jobTemplates",
  "priceBreakdowns",
  "creditCards",
  "chartOfAccounts",
  "vendorOrders",
  "vendorInvoices",
  "vendorReceiving",
  "vendorQuotations",
  "shipments",
  "ncrReports",
  "users",
  "employees",
  "documents",
  "journalEntries",
];

export const GLOBAL_SEARCH_CATEGORY_PERMISSION: Partial<
  Record<keyof GlobalSearchResults, string>
> = {
  customers: "/masters/customer",
  vendors: "/masters/vendor",
  products: "/masters/product",
  rawMaterials: "/masters/raw-material",
  orders: "/orders/customer",
  quotations: "/quotations/customer",
  invoices: "/orders/customer-invoices",
  jobOrders: "/job-orders",
  banks: "/masters/bank",
  workstations: "/masters/workstation",
  locations: "/masters/location",
  processes: "/masters/process",
  jobTemplates: "/masters/jobtemplate",
  priceBreakdowns: "/masters/pricebreakdown",
  creditCards: "/masters/creditcard",
  chartOfAccounts: "/masters/chartofaccounts",
  vendorOrders: "/purchasing/vendor-orders",
  vendorInvoices: "/purchasing/vendor-invoices",
  vendorReceiving: "/purchasing/vendor-receiving",
  vendorQuotations: "/quotations/vendor",
  shipments: "/orders/customer-shipments",
  ncrReports: "/quality",
  users: "/user-management",
  employees: "/masters/employee",
  documents: "/documents",
  journalEntries: "/accounts/journal-entries",
};
